import Header from "@/components/atoms/Header/Header"
import "./globals.scss"
import type { Metadata } from "next"
import { Noto_Sans, Cormorant_Garamond } from "next/font/google"
import Footer from "@/components/atoms/Footer/Footer"

const noto = Noto_Sans({
  variable: "--font-noto",
  weight: ["400", "600", "100"],
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${noto.variable}`}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
